# Generated by Django 3.1.6 on 2021-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, verbose_name='Uuid')),
                ('name', models.CharField(max_length=300, verbose_name='Client Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('postcode', models.IntegerField()),
            ],
        ),
    ]
